name: LifeLink CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: life_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, pdo, pdo_mysql, curl, xdebug

    - name: Install PHP dependencies
      run: composer install

    - name: Initialize MySQL schema
      run: |
        sudo apt-get install -y mysql-client
        mysql -h 127.0.0.1 -P 3306 -u root -proot life_test < db/life_test.sql

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit

    - name: Generate PHPUnit coverage report
      run: |
        rm -rf coverage/
        ./vendor/bin/phpunit --coverage-html coverage/

    - name: Upload PHPUnit coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: php-code-coverage
        path: coverage/

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        cd flask
        pip install -r requirements.txt

    - name: Start Flask API in background
      run: |
        cd flask
        nohup python3 app.py &
        sleep 5

    - name: Run Flask Unit Tests (if any)
      run: |
        cd flask
        pytest || echo "No tests yet"
